/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-container': '#06b6d4',
        tertiary: '#bdc7d9',
        'on-tertiary': '#27313f',
        'secondary-fixed': '#dce2f7',
        'on-error': '#690005',
        'primary-fixed': '#acedff',
        background: '#0d141d',
        'surface-container': '#192029',
        'on-secondary': '#293040',
        'inverse-surface': '#dce3f0',
        'surface-container-lowest': '#080f17',
        'surface-container-low': '#151c25',
        'on-background': '#dce3f0',
        'tertiary-fixed': '#d9e3f6',
        'on-primary': '#003640',
        error: '#ffb4ab',
        'on-primary-fixed': '#001f26',
        surface: '#0d141d',
        'inverse-primary': '#00687a',
        'on-tertiary-fixed-variant': '#3d4756',
        'surface-container-highest': '#2e353f',
        'on-tertiary-container': '#333d4b',
        outline: '#869397',
        'on-primary-container': '#00424f',
        'primary-fixed-dim': '#4cd7f6',
        'surface-bright': '#333a44',
        'surface-tint': '#4cd7f6',
        'outline-variant': '#3d494c',
        'inverse-on-surface': '#2a313b',
        'on-surface-variant': '#bcc9cd',
        'tertiary-container': '#9da7b9',
        'tertiary-fixed-dim': '#bdc7d9',
        'on-secondary-fixed': '#141b2b',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#004e5c',
        'secondary-container': '#404758',
        'on-surface': '#dce3f0',
        'surface-dim': '#0d141d',
        'surface-variant': '#2e353f',
        'surface-container-high': '#232a34',
        primary: '#4cd7f6',
        'on-tertiary-fixed': '#121c2a',
        secondary: '#c0c6db',
        'on-secondary-container': '#aeb5c9',
        'secondary-fixed-dim': '#c0c6db',
        'on-secondary-fixed-variant': '#404758',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'container-padding-mobile': '16px',
        'component-gap': '12px',
        unit: '4px',
        'container-padding-desktop': '32px',
      },
      fontFamily: {
        'data-mono': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      animation: {
        'slide-in-right': 'slide-in-right 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        shimmer: 'shimmer 1.5s infinite',
      },
      keyframes: {
        'slide-in-right': {
          from: { transform: 'translateX(20px)', opacity: '0' },
          to: { transform: 'translateX(0)', opacity: '1' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
    },
  },
  plugins: [],
};
